BASE <https://example.org/medical-access/>
PREFIX schema: <https://schema.org/>

SELECT ?ward (COUNT(DISTINCT ?facility) AS ?count)
WHERE {
    ?facility schema:address ?address .

    ?address schema:addressLocality ?ward .
}
GROUP BY ?ward
ORDER BY DESC(?count)
